"use client";
import FullPageLayout from "@/app/layout/FullPageLayout";
import Image from "next/image";
import Logo from "@/app/images/logo/logo.svg";

//import AuthContext from "@/app/context/auth-context";
//import { Metadata, ResolvingMetadata } from 'next';
import useAuth from "@/app/hooks/useAuth";
import { setCookie } from "cookies-next";
import Link from "next/link";

/*
export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}
*/
const url = process.env.NEXT_PUBLIC_API_URL;
const app_name: any = process.env.NEXT_PUBLIC_API_URL;

const Home = () => {
  return (
    <FullPageLayout>
      <div className="sm:flex sm:items-center sm:justify-center p-1.5 h-[calc(100vh)] md:h-[calc(100vh-12rem)]">
        <div className="lmd:h-[calc(100vh-8rem)] md:h-[calc(100vh-12rem)] lg:h-[calc(100vh-12rem)] flex items-stretch sm:rounded-[50px] sm:my-[5%]  sm:shadow-[0_0_50px_rgba(0,0,0,0.3)]">
          <div className="hidden lmd:block lg:block w-full xl:block md:w-1/2 xl:w-1/2 rounded-l-[50px]">
            <div className="flex h-full w-full items-center justify-center px-10">
              <div className=" h-45 w-45  rounded-full flex items-center justify-center bg-white">
                <a href="/">
                  <Image src={Logo} alt={app_name} height={100} />
                </a>
              </div>
            </div>
          </div>

          <div className="w-full  flex items-center justify-center border-[#E69A52]  xl:w-1/2 xl:border-l-2">
            <div className="flex flex-col items-center justify-center gap-5 p-4 sm:p-12.5 xl:p-17.5">
              <div className="sm:hidden w-full rounded-md flex items-center justify-center h-40 bg-[#43ACD6]">
                <div className="h-35 w-35  rounded-full bg-white flex items-center justify-center shadow-[0_0_50px_rgba(0,0,0,0.3)]">
                  <a href="/">
                    <Image src={Logo} alt={app_name} height={100} />
                  </a>
                </div>
              </div>
              <Link className="text-lg font-bold  text-white" href="/member">
                Client Login
              </Link>

              <Link className="text-lg font-bold  text-white" href="/admin">
                Admin Login
              </Link>
            </div>
          </div>
        </div>
      </div>
    </FullPageLayout>
  );
};
/*
export async function generateMetadata() {
  // read route params then fetch data

  // return an object
  return {
    title: 'Login',
    //description: '',
  };
}
*/

export default Home;
